// Mirror of the Rust Project/Clip types. Keep in sync with src-tauri/src/lib.rs.

export type ClipStatus =
  | "draft"
  | "frames_extracted"
  | "narrated"
  | "audio_ready"
  | "rendered";

export interface Clip {
  id: string; // "01", "02", ...
  source_name: string;
  bytes: number;
  duration_seconds: number | null;
  title: string;
  /** Per-clip overview narration shown at the start of this section.
   *  Generated by generate_overview after the clip is narrated. Editable. */
  overview: string;
  status: ClipStatus;
}

export interface Project {
  version: number;
  name: string;
  opening_title_text: string;
  main_prompt: string;
  /** BCP-47 language tag. Phase 1: always "en", no UI to change it.
   *  Phase 2 will expose a selector and use it to drive narration prompt,
   *  TTS engine, and caption font. See lib.rs Project::language for details. */
  language: string;
  created_at: string; // ISO8601 UTC
  clips: Clip[];
  // `dir` is intentionally absent in the serialized JSON — Rust adds it on load.
  // We rely on it being present on every Project the UI holds.
  dir: string;
}

export interface FrameInfo {
  name: string; // "0001.jpg"
  path: string; // absolute path to the JPG on disk
  timestamp_seconds: number | null; // null for PPTX slides
}

export interface ExtractResult {
  project: Project;
  frames: FrameInfo[];
}

export interface NarrationEntry {
  name: string;
  timestamp_seconds: number | null;
  hash: string;
  text: string | null;
  inherits_from: string | null;
}

export interface Narration {
  version: number;
  entries: NarrationEntry[];
}

export interface NarrationProgress {
  clip_id: string;
  index: number;
  total: number;
  name: string;
  text: string | null;
  inherited: boolean;
}

export interface TtsProgress {
  clip_id: string;
  index: number;
  total: number;
  name: string;
  stage: "loading" | "loaded" | "progress" | "done";
  duration_seconds: number | null;
}

export interface AudioManifestEntry {
  frame_name: string;
  audio_name: string;
  timestamp_seconds: number | null;
  duration_seconds: number;
}

export interface AudioManifest {
  version: number;
  entries: AudioManifestEntry[];
}

export interface RenderProgress {
  stage: string;
  detail: string;
  fraction: number; // 0-1 or -1 for indeterminate
}

// Phase 1.7 — scan / plan / script types.
export interface KeyFrame {
  name: string; // "0007.jpg"
  type: "section_divider" | "step";
  summary: string;
  title?: string | null;
  ui_action?: string | null;
  implicit_topic?: string | null;
}

export interface Scan {
  version: number;
  narrative_arc: string;
  inferred_mode: "step_by_step" | "showcase" | "mixed";
  key_frames: KeyFrame[];
}

export interface ScanProgress {
  clip_id: string;
  stage: "thumbnails" | "calling_ai" | "parsing" | "saving" | "done" | string;
  detail: string;
  fraction: number;
}

// Phase 1.7c — plan
export type ScriptUnitKind = "title_card" | "instruction" | "filler";

export interface ScriptUnit {
  id: string;
  type: ScriptUnitKind;
  frames: string[];
  text?: string | null;
}

export interface PlanSection {
  id: string;
  title: string;
  overview: string;
  units: ScriptUnit[];
}

export interface Plan {
  version: number;
  sections: PlanSection[];
  excluded_frames: string[];
}
